version: '3.4'

services:
  database:
    image: mariadb:10.4.7-bionic
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=backend_java
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
