version: '3.4'

services:
  app:
    init: true
    image: equipo01-backend-java:test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./reports/:/app/target/surefire-reports/
